/* ===== CONTROLADOR · js/controller/tasks.js =====
   Controlador de tareas: crear, completar, editar, borrar. */
function addTD(){const v=$('#cd').value.trim();if(!v)return $('#cd').focus();S.tasks.push({id:uid(),title:v,p:'',due:selD,pri:0,note:'',done:false});save();vCal()}
function addTH(){const i=$('#th'),v=i.value.trim();if(!v)return i.focus();const dv=$('#thd').value||'';S.tasks.push({id:uid(),title:v,p:'',due:dv,pri:0,note:'',done:false});newId=S.tasks[S.tasks.length-1].id;save();draw();avisa(v,dv)||toast('Tarea agregada');const j=$('#th');if(j)j.focus()}
function addT(){const v=$('#tt').value.trim();if(!v)return $('#tt').focus();const dv=$('#tdd').value||'';S.tasks.push({id:uid(),title:v,p:'',due:dv,pri:0,note:'',done:false});newId=S.tasks[S.tasks.length-1].id;if(tf==='hecha')tf='pend';save();draw();avisa(v,dv)||toast('Tarea agregada');const i=$('#tt');if(i)i.focus()}
const togT=id=>{const t=S.tasks.find(t=>t.id===id);newId=id;t.done=!t.done;t.doneAt=t.done?today():'';if(t.done&&t.rep&&t.due&&!t.nx){t.nx=1;S.tasks.push({...t,id:uid(),done:false,doneAt:'',nx:0,due:addR(t.due,t.rep),subs:(t.subs||[]).map(x=>({...x,d:false}))})}save();draw()};
function dropT(e,k){e.preventDefault();const t=S.tasks.find(x=>x.id===e.dataTransfer.getData('text/plain'));if(t){t.due=k;save();draw();toast('Tarea movida')}}
function avisa(n,k){if(!k)return false;const d=dd(k);if(d>(S.adv||7))return false;toast('⚠ '+n+' · '+venceTxt(d));clearTimeout(toast.h);toast.h=setTimeout(()=>$('#toast').style.display='none',5500);return true}
function saveT(id){const t=S.tasks.find(t=>t.id===id),v=$('#e1').value.trim();if(!v)return $('#e1').focus();subAdd();Object.assign(t,{title:v,p:$('#e2').value,due:$('#e3').value,pri:+$('#e4').value,note:$('#e5').value,time:$('#e6').value,rep:$('#e7').value,subs:ed});avisa(v,$('#e3').value);save();closeM();draw();toast('Cambios guardados')}
const delT=id=>{const t=S.tasks.find(x=>x.id===id),i=S.tasks.indexOf(t);S.tasks=S.tasks.filter(x=>x.id!==id);(S.del=S.del||{})[id]=1;save();closeM();draw();undoT('Tarea eliminada',()=>{delete S.del[id];S.tasks.splice(Math.min(i,S.tasks.length),0,t);save();draw()})};
