/* ===== VISTA · js/view/screens/archivos.js =====
   Pantalla Archivos y visor. */
let fq='';
function vArchivos(){const q=fq.toLowerCase(),l=fsort(S.files.filter(f=>(ff==='todo'||f.k===ff)&&(!q||f.name.toLowerCase().includes(q)))),n=k=>S.files.filter(f=>k==='todo'||f.k===k).length;$('#main').innerHTML=`<h2>Archivos</h2><p class="sub">Imágenes, videos y presentaciones.</p><div class="dz" id="dz"><input type="file" id="fi" multiple hidden onchange="fiCh()"><div class="dzi">⬆</div><div><b>Arrastra tus archivos aquí</b><div class="m" id="dzt">o elígelos desde tu dispositivo</div></div><button class="btn g" onclick="$('#fi').click()">Elegir archivos</button><select id="fp" aria-label="Proyecto">${popts()}</select><button class="btn" onclick="addF()">Subir</button><div class="ub" id="bar"><i></i></div></div><div class="row"><input type="text" id="fq" placeholder="Buscar archivos…" aria-label="Buscar archivos" value="${esc(fq)}" oninput="fSearch(this.value)" style="max-width:280px"><select aria-label="Ordenar archivos" onchange="fso=this.value;vArchivos()"><option value="nuevo">Orden: Más recientes</option><option value="nombre" ${fso==='nombre'?'selected':''}>Orden: Nombre</option><option value="tam" ${fso==='tam'?'selected':''}>Orden: Tamaño</option></select></div>${chips([['todo','Todo '+n('todo')],['img','Imágenes '+n('img')],['vid','Videos '+n('vid')],['pres','Presentaciones '+n('pres')],['otro','Otros '+n('otro')]],ff,'setFf')}${db?'':'<p class="m">Este navegador no permite guardar archivos.</p>'}<div class="fg" id="fgrid">${l.map(fileCard).join('')||'<div class="empty">Sin archivos aquí.</div>'}</div>`;loadPv(l);const dz=$('#dz');dz.ondragover=e=>{e.preventDefault();dz.classList.add('ov')};dz.ondragleave=()=>dz.classList.remove('ov');dz.ondrop=e=>{e.preventDefault();dz.classList.remove('ov');$('#fi').files=e.dataTransfer.files;fiCh()}}
function fiCh(){const k=$('#fi').files.length;$('#dzt').textContent=k?k+' archivo'+(k==1?'':'s')+' listo'+(k==1?'':'s')+' para subir':'o elígelos desde tu dispositivo'}
let fso='nuevo';
const fsort=l=>fso==='nombre'?[...l].sort((a,b)=>a.name.localeCompare(b.name)):fso==='tam'?[...l].sort((a,b)=>b.size-a.size):[...l].reverse();
function editF(id){const f=S.files.find(x=>x.id===id);openM(`<div class="box"><b>Editar archivo</b><input type="text" id="f1" value="${esc(f.name)}" aria-label="Nombre"><select id="f2" aria-label="Proyecto">${popts(f.p)}</select><div class="row" style="margin:0"><button class="btn" onclick="saveF('${id}')">Guardar cambios</button><button class="btn g" onclick="closeM()">Cancelar</button></div></div>`)}
function fSearch(v){fq=v;const q=v.toLowerCase(),l=fsort(S.files.filter(f=>(ff==='todo'||f.k===ff)&&(!q||f.name.toLowerCase().includes(q))));$('#fgrid').innerHTML=l.map(fileCard).join('')||'<div class="empty">Sin archivos aquí.</div>';loadPv(l)}
let vi=null,vx0=0;
async function openV(id){const l=S.files.filter(x=>(ff==='todo'||x.k===ff)&&(x.k==='img'||x.k==='vid')),i=l.findIndex(x=>x.id===id);if(i<0)return;if(!vi)hPush();vi={l,i};await showV()}
async function showV(){const f=vi.l[vi.i],u=await blobUrl(f.id);if(!u)return;let w=$('#vw');if(!w){w=document.createElement('div');w.id='vw';w.onclick=e=>{if(e.target===w)closeV()};document.body.appendChild(w)}const dv=new Date(f.created||parseInt(f.id.slice(0,-4),36)),d=isNaN(dv)?'':dv.toLocaleDateString('es',{day:'numeric',month:'short',year:'numeric'});w.innerHTML=`<button class="vx" onclick="closeV()" aria-label="Cerrar">×</button>${vi.l.length>1?'<button class="vn vl" onclick="stepV(-1)" aria-label="Anterior">‹</button><button class="vn vr" onclick="stepV(1)" aria-label="Siguiente">›</button>':''}${f.k==='img'?`<img src="${u}" alt="${esc(f.name)}">`:`<video src="${u}" controls autoplay playsinline></video>`}<div class="cap"><b>${esc(f.name)}</b><div class="m">${size(f.size)} · ${d} · ${esc(pn(f.p))} · ${vi.i+1}/${vi.l.length}</div><button class="btn g" onclick="dlF('${f.id}')">Descargar</button></div>`;w.ontouchstart=e=>{vx0=e.touches[0].clientX};w.ontouchend=e=>{const dx=e.changedTouches[0].clientX-vx0;if(Math.abs(dx)>60&&vi&&vi.l.length>1)stepV(dx<0?1:-1)}}
const stepV=n=>{vi.i=(vi.i+n+vi.l.length)%vi.l.length;showV()};
function closeV(fp){const w=$('#vw'),had=!!vi;if(w)w.remove();vi=null;if(had&&fp!==true)hBack()}
document.addEventListener('keydown',e=>{if(!vi)return;if(e.key==='Escape')closeV();else if(e.key==='ArrowRight')stepV(1);else if(e.key==='ArrowLeft')stepV(-1)});
